In [4]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("/employee_salary.csv")
df.head()

    id   name     dept   salary
0  101   john       HR  50000.0
1  102   ram        IT      NaN
2  103  priya   design  40000.0
3  104    sam       PR  35000.0
4  105  shyam  manager      NaN

In [7]:
df.tail()

    id   name     dept   salary
2  103  priya   design  40000.0
3  104    sam       PR  35000.0
4  105  shyam  manager      NaN
5  106  steve       IT  45000.0
6  106  steve       IT  45000.0

In [8]:
df.shape

(7, 4)

In [9]:
df.columns

Index(['id', 'name', 'dept', 'salary'], dtype='object')

In [10]:
df.dtypes

id          int64
name       object
dept       object
salary    float64
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      7 non-null      int64
 1   name    7 non-null      object
 2   dept    7 non-null      object
 3   salary  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 356.0+ bytes

In [12]:
df.describe()

               id        salary
count    7.000000      5.000000
mean   103.857143  43000.000000
std      1.951800   5700.877125
min    101.000000  35000.000000
25%    102.500000  40000.000000
50%    104.000000  45000.000000
75%    105.500000  45000.000000
max    106.000000  50000.000000

In [13]:
df.isnull().sum()

id        0
name      0
dept      0
salary    2
dtype: int64

In [14]:
missing_data = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percentage': (df.isnull().sum() / len(df)) * 100
})

print(missing_data)

        Missing Count  Missing Percentage
id                  0            0.000000
name                0            0.000000
dept                0            0.000000
salary              2           28.571429

In [15]:
df.isnull().sum().idxmax()

'salary'