In [ ]:
import pandas as pd
wavelength=[120,119,170,127,121,146,137,190,161,145,141,132]
bins=[118,125,135,160,200]

In [ ]:
category=pd.cut(wavelength,bins)
category

[(118, 125], (118, 125], (160, 200], (125, 135], (118, 125], ..., (160, 200], (160, 200], (135, 160], (135, 160], (125, 135]]
Length: 12
Categories (4, interval[int64, right]): [(118, 125] < (125, 135] < (135, 160] < (160, 200]]

In [ ]:
pd.value_counts(category)

/tmp/ipykernel_578/2654243906.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category)

(135, 160]    4
(118, 125]    3
(160, 200]    3
(125, 135]    2
Name: count, dtype: int64

In [ ]:
names=["short wavelength","average wavelength","long wavelength","good wavelength"]
pd.cut(wavelength,bins,labels=names)

['short wavelength', 'short wavelength', 'good wavelength', 'average wavelength', 'short wavelength', ..., 'good wavelength', 'good wavelength', 'long wavelength', 'long wavelength', 'average wavelength']
Length: 12
Categories (4, object): ['short wavelength' < 'average wavelength' < 'long wavelength' <
                         'good wavelength']

In [ ]:
import numpy as np
print(np.random.rand(40))

[0.21669654 0.01446792 0.72276604 0.57368364 0.66955107 0.25158846
 0.12415734 0.28721807 0.40287335 0.99068991 0.42342658 0.10373234
 0.32818138 0.80231195 0.24613446 0.48383292 0.02951932 0.09244695
 0.82900989 0.00167073 0.87188822 0.15129469 0.10251889 0.72711817
 0.03284888 0.74843122 0.49711407 0.75129065 0.86780974 0.55946837
 0.06462169 0.42334854 0.10868748 0.46175439 0.37932309 0.48625636
 0.4084266  0.12643618 0.38186464 0.85807899]

In [ ]:
pd.cut(np.random.rand(40),5,precision=2)

[(0.41, 0.6], (0.02, 0.22], (0.41, 0.6], (0.02, 0.22], (0.41, 0.6], ..., (0.8, 0.99], (0.8, 0.99], (0.6, 0.8], (0.02, 0.22], (0.8, 0.99]]
Length: 40
Categories (5, interval[float64, right]): [(0.02, 0.22] < (0.22, 0.41] < (0.41, 0.6] < (0.6, 0.8] <
                                           (0.8, 0.99]]

In [ ]:
randomnums=np.random.rand(2000)
category3=pd.qcut(randomnums,4)
category3

[(0.51, 0.746], (0.252, 0.51], (0.252, 0.51], (0.0002899999999999999, 0.252], (0.0002899999999999999, 0.252], ..., (0.252, 0.51], (0.51, 0.746], (0.252, 0.51], (0.746, 1.0], (0.252, 0.51]]
Length: 2000
Categories (4, interval[float64, right]): [(0.0002899999999999999, 0.252] < (0.252, 0.51] < (0.51, 0.746] <
                                           (0.746, 1.0]]

In [ ]:
pd.value_counts(category3)

/tmp/ipykernel_578/647498483.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category3)

(0.0002899999999999999, 0.252]    500
(0.252, 0.51]                     500
(0.51, 0.746]                     500
(0.746, 1.0]                      500
Name: count, dtype: int64

In [ ]:
df=pd.read_csv("/content/fraudTest.csv")
df.head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
5,5,2020-06-21 12:15:37,30407675418785,fraud_Daugherty LLC,kids_pets,19.55,Danielle,Evans,F,76752 David Lodge Apt. 064,...,42.1939,-76.7361,520,Psychotherapist,1991-10-13,798db04aaceb4febd084f1a7c404da93,1371816937,41.747157,-77.584197,0
6,6,2020-06-21 12:15:44,213180742685905,fraud_Romaguera Ltd,health_fitness,133.93,Kayla,Sutton,F,010 Weaver Land,...,40.5070,-123.9743,1139,"Therapist, occupational",1951-01-15,17003d7ce534440eadb10c4750e020e5,1371816944,41.499458,-124.888729,0
7,7,2020-06-21 12:15:50,3589289942931264,fraud_Reichel LLC,personal_care,10.37,Paula,Estrada,F,350 Stacy Glens,...,43.7557,-97.5936,343,"Development worker, international aid",1972-03-05,8be473af4f05fc6146ea55ace73e7ca2,1371816950,44.495498,-97.728453,0
8,8,2020-06-21 12:16:10,3596357274378601,"fraud_Goyette, Howell and Collier",shopping_pos,4.37,David,Everett,M,4138 David Fall,...,41.0001,-78.2357,3688,Advice worker,1973-05-27,71a1da150d1ce510193d7622e08e784e,1371816970,41.546067,-78.120238,0
9,9,2020-06-21 12:16:11,3546897637165774,fraud_Kilback Group,food_dining,66.54,Kayla,Obrien,F,7921 Robert Port Suite 343,...,31.6591,-96.8094,263,Barrister,1956-05-30,a7915132c7c4240996ba03a47f81e3bd,1371816971,31.782919,-96.366185,0

In [ ]:
df['totalamt']=df['amt']*20
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,fine,totalamt
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,57.2,57.2
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,596.8,596.8
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0,825.6,825.6
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0,1201.0,1201.0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0,63.8,63.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0,875.4,875.4
555715,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0,2236.8,2236.8
555716,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0,1737.6,1737.6
555717,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0,159.8,159.8
555718,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0,762.6,762.6

In [ ]:
totaltrans=df["totalamt"]
totaltrans[np.abs(totaltrans)>1000]

3         1201.0
6         2678.6
9         1330.8
18        1602.2
30        3524.6
           ...
555705    2476.8
555706    1096.2
555707    2685.2
555715    2236.8
555716    1737.6
Name: totalamt, Length: 266789, dtype: float64

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [ ]:
data={'Age': [17,24,21,19,20],'Salary':[3500,4300,6000,13000,6600]}
df=pd.DataFrame(data)
print("original data:\n",df,"\n")

original data:
    Age  Salary
0   17    3500
1   24    4300
2   21    6000
3   19   13000
4   20    6600

In [ ]:
min_max_scaler=MinMaxScaler()
df_min_max=pd.DataFrame(
 min_max_scaler.fit_transform(df),
 columns=df.columns
)
print("Min-Max Scaled Data:\n", df_min_max, "\n")

Min-Max Scaled Data:
         Age    Salary
0  0.000000  0.000000
1  1.000000  0.084211
2  0.571429  0.263158
3  0.285714  1.000000
4  0.428571  0.326316

In [ ]:
standard_scaler=StandardScaler()
df_standard=pd.DataFrame(standard_scaler.fit_transform(df),columns=df.columns)
print("Standardized Data:\n", df_standard, "\n")

Standardized Data:
         Age    Salary
0 -1.382189 -0.948616
1  1.641350 -0.709970
2  0.345547 -0.202849
3 -0.518321  1.885299
4 -0.086387 -0.023865